# Mod
mod_id = shogi
mod_name = Shogi
mod_author = BlayTheNinth
credits = BlayTheNinth
description = Rule-based properties and configuration for everything
version = 26.1.0.0
group = net.blay09.mods
homepage=https://balm.twelveiterations.com
sources=https://github.com/TwelveIterations/Shogi
issues=https://github.com/TwelveIterations/Shogi/issues
discord = https://discord.gg/VAfZ2Nau6j
license = MIT

# Publishing
curseforge_project_id = 531761
modrinth_project_id = bi4iCmsw
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Minecraft
java_version = 25

# NeoForge
neoforge_snapshot_url =

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
