modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="shogi_api"
version="${version}"
displayName="Shogi API"
displayURL="${homepage}"
authors="${mod_author}"
description='''${description}'''
[[dependencies.shogi_api]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.shogi_api]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
