plugins {
    id 'multiloader-common'
    alias libs.plugins.modDevGradle
}

base {
    archivesName = "${project.name}"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "shogi-api"
        }
    }
}

neoForge {
    neoFormVersion = libs.neoForm.get().version
    parchment.parchmentArtifact = libs.parchment.get().toString()
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

